### ISSUE TITLE
Peer-2-Peer Review: Fix font-family and logo `rotation` issue 

### ISSUE THREAD

**Issue by MrBrN197** [den-cloud/Portfolio_Website#17]
on line [3](https://github.com/den-cloud/Portfolio_Website/blob/d0fc18af3051028b68b16832bbc745d11532a270/styles.css#L3) you can add `font-family: Poppins, sans-serif;` to the `body` tag to ensure all text is using that font. 

on line [90-91](https://github.com/den-cloud/Portfolio_Website/blob/d0fc18af3051028b68b16832bbc745d11532a270/styles.css#L90-L91) if you want the rotate to start every time someone comes to the page you must use a `animtion` property instead and create an animation for it to use. 

### Example

```css
.logo {
  animation: rotation 1s;
}

@keyframes rotation {
  0% {transform: rotate(0);}
  100% {transform: rotate(360deg);}
}
```
